name: Publish to PyPi
on:
    push:
        branches: 'main'
jobs:
    publish:
        runs-on: 'ubuntu-20.04'
        env:
            POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9.10'
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.4.2
            - name: Install Project
              run: poetry install
            - name: Build Project
              run: poetry build
            - name: Publish to PyPi
              run: poetry publish
